---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-brc-advanced-search
  namespace: brc-advanced-search
spec:
  encryptedData:
    .dockerconfigjson: AgBEihFkSogczxJRDCXAkaorI456XHADcPXiTLHvEE9DofMwSou5Cpoa95nnkOHNzpMY2Ui2ovdTWeNXQPxdmt8+LyZvuf6ZCMhbvPVqulW0VimqNVPqQD46howjmZON7lBt/oG0LDboafXhPaE+fc/ZAYiAhCgqfV8keP1v3PVm3wPpelT/E0EHC2zcD2TpAqFboxkB318peCr+YDJBEl/c3SiTbVJqm8QebnVEiOs0Tr6BIOR92H586nc0JyszzTXzLmBo8W2Wy/WL6FNz0G3vzoKSaQP6OSdqyhTQow4XO4CJLqRM7fe4ioXhY6YXaHB29Et0ar+eunbKIXEeeZPrdSRcePubWWjM0HShB35KvwqqvyBG5gMyjdGzVYX1umksrqK6gbTbLZMw18CulpiJeXn5FFpyylz3oXip9cBNZ9VXQDZCgR+M7y1WFpYSANCyN1+dTfXdVpPzY6SpT2/EL/v+zXK8KsEMNGVdkdhZ29OSfkps+bJ+Tln0h7PqS0wHuirl/RGXQd++Q0uX2QxYa/AO40u5Nq2ufnkIP4xttURffJteC6FAwpxANqu8sCQR063kg9vPVYD4d3q9QKl0Wktzr+Y0lMhXuamQ20Tpu5mwMcT65QgJCdZH7QDusm/T/29ZL5zFFKtYlR33lTw5OsyZu+rLkuW4F/uLyjsGEhc1yrQu+PNpDMM07yr1dNpfB65hQWcnIN5HFbH6P6UrHev36wRxxb1UNua2iTGXx/xWD4OYnvB/uD5tsUSeogQjrW6HivEtiNLmVuI27OseEU69TNryzL39ZMPzMatbCYZa1EsOa8MIqESytfSEa1RCKwWD1p0lO5SxhJ1sQkRm4jF6mbMqhpi55KzP4/FLyHmYhAIzOibv7Yw+bCK0tUyvkZxIwxOHU8+/7dq1FWMjdJXX8IQL890bg/5HUJsHqf0fIGsdIADc2Izt3uDDlbhGB0XQb2EsreF/+/fJx/pqWUqv79+DYCUXot9E
  template:
    metadata:
      name: ghcr-brc-advanced-search
      namespace: brc-advanced-search
    type: kubernetes.io/dockerconfigjson
