---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-brc-advanced-search
  namespace: brc-advanced-search
spec:
  encryptedData:
    .dockerconfigjson: AgAIZoHd4c93og99tw5abrfmh6m3MZwRH3BBW5Vit2yTpJbto7ScyxpM6edfVtcFrxaIJlMnKiAGgEEfiG96fwyy+AEgMDYzdfD77PhCuRomyyXksaLlLQSRdlDTLpZ0876LUuDPPt9BITnmRzOIHAQzNZwoAzUAy29nizfkblQP6+1rIVWKASjL7bUV4egaegX4i13TtVaPOkvrrOvjWgRerPqVfzoJIXJX0LHIdjYFMxGnwSHAP/e7lb7T95/SGL3NmmHdkvjWXZLoV6jRHr1+CEmWSZbhrxuMIhkNfqDPnANAqqyS5AtwSVZQvDtWOPNlpoH5zvkRVSUCh1yde3yts3HTGlj2IF/azAhEPI7dtkZcB7fgGZh3mzOV2by4NPJ57ifIjhoeTpNejYmYfDawCP0N+sDx3tTd5TGi1SKCuytUQd4kT2WKGwyLrnYB7YmvuxzuyQ06OoYFNGSJc1PcAMPeXVIrD3mA9Z0Ga4lDOzLIdiNJ6WDHa17kjYqUNQil6l3gadrKBCG9MbcqdBBb5AHky6E5hvbIboCW0b+dpF5t/VvXVO/DMlksD6dafsfF11/fT/ZZzulMbGM7Jd1DVjwFe1EW2RQ5KTOWWEBEK8jjGMCBtRihq4rWLAFk3pHqwZe3gQvmik9m2rHAjDD7ckssOZ5gCZ88tzeqgCQizemrFZpY0B2KZ4eCeNt+beXbeVcdGJ5uutfUHqc735cKxGjmJZxXEBShQmRgaEoSfpNxTsJ+tyUgDOc/qCHNbeGtKHDJ4OnUOQvmnWlaVlpoyRuMSWldWWSNtzS4KfZiA2pZIBCtTIkPywI+RLXYi1hx81P2wZu99djSiYR0hqhsmUS8sv0Rdy0B1eUxwike044HZk/yvqoEhNJieQ0nnyVEiTmHwnMSTzDmrb96RzYGfa6o5IHzojefcBOZBtPIHJ7QtCEGrFxV0Q==
  template:
    metadata:
      name: ghcr-brc-advanced-search
      namespace: brc-advanced-search
    type: kubernetes.io/dockerconfigjson
