---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-brc-advanced-search
  namespace: brc-advanced-search
spec:
  encryptedData:
    .dockerconfigjson: AgAS9IxWeh1KtiOglMYy8o4uOPhFm75b6TfE6gCejPsDkkQ8QouclT3ERdC3YbN6L2eYnaPBw/R1gQHxJximqQ6RjCxTrtEvVMjvQlkLp7Q1CP35c0+OSH2yAazyJwINzmBuPEO4WE5NwBZZUT91S5fwQsmC0DQd76eENMBj4LYLNmSMZ8j+ReAwSvXy81EeCRW+MAKRQVj/GP8S4DvtuHjrQhGztq4FnH+e5bwRHaFcgAjMpPX3jEPChgeid/tP3WEBc6o/ZFFsE5yK0/6LDJy7gObl7OBST42ZtCU5Gk7svkQGn1+bOb4uOfEJRS4vfzbIoheB0MTobcpazOEC9dq0Onu6ANe97OjLR14f9WQ1AeAmGNfCayFd+ZcCEotLBU00XzKKZNK2wIwR1wShWisCtHJWxBTBQZvMGFYsi/R4MV9bkIS9fHDaQWTa2SwXOXBCkvi2wWRwnLo5CkZcKHARKSDUNDOXfpceGxP0hpSC5vKnYDG3BaMbI+ljcGsVYLUuu6LRcaFB0JNCqSZpAkbH9dLE0LMJB71O9GCHCeZ8avELkU+ZcnBiO06VJXgwiOAkYFk2VpTHK9Dh2jJw1kZsg5Ilh0I2G+ZjKuewL/nO/y8zfr6SoEqJ4D+uW4aAVSdMVBTymG/moXGvt8yJ/LRofadMkZCHoVxaELAQ411ppPiMOkiBtAD69LdnqFLR4+v13tJq/X71liA3oZKUVChL2vPaTHmJl0/Ig3hnCetcjQUydP5CcqOg5PdhSp412Jdg0XaZ3Q6sjzoihBOGJrN3uiWH0gYEryqP2gELDjGeHyTbQQZahD1vRnAjdZ0T3Sicb9l1rO3jxtaw+JEYDRPn4DkM/1ZzmKpeJ0Dp0vu6t7YBJUrdBx3gP2vEl6fwrVBxyW77F/8Bn6K+dwpNdVrrV6Xob1y9y1uqQB5rXj/h4rp2ERWHTyUHMZMIOYIyAEUNFg==
  template:
    metadata:
      name: ghcr-brc-advanced-search
      namespace: brc-advanced-search
    type: kubernetes.io/dockerconfigjson
