---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-metadatabase-v2
  namespace: metadatabase-v2
spec:
  encryptedData:
    .dockerconfigjson: AgAGgK5AeZBDb7Z+I/gsY7g3GkfA9R5mdQsjisrZIUfqYjAqLRleIUVcUJ2g97fj4PAb6Ve84mDzEHq55Mh3PiqX08cL+lviqg5rQQeAOFV75dbIJR4ErrP9W3zTkv+b+6sXFOa9idy3PIOGua7+4HooaXMPzSbSMgZIxlS1sioEjdqJhTbYeUG7Dicd+evgNmfoMZ1PJYjpvwrJK9XBJsfI6Wd73kOZkAzI740KdEL+yMSAC+0+FigJwHz+2+J+4nZtLj55uIYfNDqEXbjAkb6pICXrGsZYne2+UuPI3GM+QBlweYGAKOxVuImRWnVH1XS/1kRLA5KxkEgvOgHOaTG4/8xiOOxbjXDcTFVJJ7q8sp917KywUCJ5SFfl0OB2rQ7+cHmEtKe1krqBSULqU2uBjcWBqwNjAMmJX+Ul+2dhaYyIaV3i0fwd3LvtH9S9n1yK4QxJzCQaoeNK+mhpUiI1aNorSodhnkSu2gd3kPPvJ7ExjE8mAWMnKoxSbirzXPseECBW1iAOVlsEKpDCLxHZz9AMiMLMkk+eAd92MbzBi523OR379cc8QgUVUmzAMaPN5gCW5xWX6MV08hfBnFnin2Jw/rL3kMr/GSJFk8O4gN2MnXab8/+CTyI0ttxZhU06lqncZwUe2KAgZhTvtvgO8qD1Lxcp2HpmQeXHJOH5kO6Tiak2LjGA5g8c8b+OLvpnsiGh3TuMvqvIvWYC37CiNL4t1kXe9/yteSNIEXELzWegdcRpMg4Dl5W4graX96SbtfjIaDHo11UsKUFBiZDa1hjcgnwcYMG3ZSFS3GdQognUKyfiSfL7ioFpgCwjsmm66B8k5NUzIBdNCnEgoFMCDt/4105pEIBnpJcjLNpjJ21YwU8GhSYizIDNiA92scCdoIUGMOj88b4Rj+1vQJul96txORc+njBFxSvkvXHJlpIQmRDcDs+p20Mcd1NiC8Zs80wJ6JwsEdssSEUEMMjwPMKqCUoU
  template:
    metadata:
      name: ghcr-metadatabase-v2
      namespace: metadatabase-v2
    type: kubernetes.io/dockerconfigjson
