---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-riken-diips
  namespace: riken-diips
spec:
  encryptedData:
    .dockerconfigjson: AgBMKVOg82dO5ULxzPcCYI2QkftMtFu2YkpSEonQ2GzYL3BDA2IDQvwE8QyuwjCRcvRGeqbIB2+/8wfYNT0o5iUiogxtehy4xFybS515bqnFlyhwj/ZDmzhfn3dvONPjXZJcgD0PzP7HUC3TBvYUAzN9Vt7XujPiigTpjGn7KI6+fWL94vGWDZaoQ5PHRdhD7KEvDUW4VISqD4Gd4TNfommMhxaOy/8rQxKAFNC7XkGh8xn73xHyDXIQxUB61Y+11AIaX44vV/gb9teVPYklw/e3OlIt3FiZnw86SF5fjgxqnJw9mUHpEyFlENikreEoCnS+WW6TAc6IFNGEJBTJVP2qBTjc/gbmBnFrGhUcZ9RYIBAOvhVL07U2ZrR8pyr1eKcSa2wW+oHD7EMQKtPilvAUteT4IlP4+cOZ2zV+1g5hm9GDk5DQN9vGCRedkNyhRpDlpLt3RLxg70fhYcU3Q3V0T4+agBeQ+HRgiui1p9rOKnrlmvLvxPcASuVY60e4Z77etbzdJtcJ1iUOCe8jZJmyCXU+VeGr3z9d0DwRQ/MPc+xO53y86AWW6BdoVv1Gp+JZTq3PwMtdT0AGP81kIst8D/VihCGn8gpLgMROn3kXheB6j6sLh6yOzLkL0mDSfaytdsmM21jWNE9HjURdwd5UisUC/GtixjvlegDX852n61EexvgdfhTRXYYXjP9NrrlHoYlhSg0PaJxCpxkdQUJuI3IMSsg+ag5bAjOPPLUOYTl+xm2+qm8dujjE34I0uehwiL0KsR1KD3akJ7L00h8a32lKlt8GxwrzhAFYjFR2mcRKla8UoiKAu8AnuWusIYdlE70sjeQN1rRdYcYTrgOtz5TA7Se2AHs3W5BEi4qD4F8GvgkifMB9upUutUTv6X7xFklUmi2IYNMwWP4Zxn5ScP3dLEsjiqXdTTrfqB2FGx7f/yEz81E1zxBcxjVj0fp+dw==
  template:
    metadata:
      name: ghcr-riken-diips
      namespace: riken-diips
    type: kubernetes.io/dockerconfigjson
