---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-riken-diips
  namespace: riken-diips
spec:
  encryptedData:
    .dockerconfigjson: AgCFzWYDjPeHGey3yRekLwnSYs/iv031+DVJgTGS8y4/sxTa5/XizRjC+AY9RiQfI9y+JGvUjeA10ycLamRdDYWm62tkTDPbTuuvQQyIhTGgHh0S+lShzhkOswINovAT8XETHCDgeq/Tp11fqdPzMqSilWUNE96KUvjjjMvFUGm4Hx+g4+RmCyUsIqKnb8aBKhJxc9TO/4QZ8qeNtJXamkWwtLUYhPR/7r+n2vHB737XRwnby2m8XjUIx+JWyN3SedStciaooldXZeqW15aHWG3n/DZgxXlIcEB3gtL/3aQZE76omqxIZU7jmrnzsg13H9ZUky2zvnz+lPqSeYwTb7QNPUDQn8BFOX7s4t824Tsss7VCq7iydVfRzd2OoSKeFrdnUiw0kPb+z6D6LHnlzKrandlhgenPK4rMzoGqMYDSVeUz0Wochkki0+3eEJl7a/R7Zxd1yuoixxVqcgEOgHvEeNLGPfbiLuqiW0naP3ntZiIiNVNXlZaoaoV/fEBSmoz728zJLIodBmJyTXGYd9SS4KaKXZ6whytqboTa0eisTrJTZGU1e94pUgbe/OzwQkCQiaSIHURqHfgo94ZRP0WI11QpUXZyQtl5dfKMvMnKeaOlmULAsDu4o7mtd5JXsAJqrfnmveakAb2+gxFpZ7JjYZNAm0SZf1eqrYShCgLrAuEXLFszXaZ1Y/CKPR06Xcw5VAWGlfs55Pl9xbn+nuO0aHy7qBLJU9asRHO+UHhh2zZpgont1t79e/Q7Af29M1GRKWESBAoIqVnsEhbZOTbGJEdFlZ1GStF3NaF0JO8MzXGiJz9zaAZVIJZajCbG6Ux7gBpsn/Na660lLRjvpK95r7HleFXXhxVm91c5jEUiPMeqegN+B07HosBO6IU4T+LhJlIiSVPqve2GtWeTTwiyuVKoa9O6O3e9LtXKeLz0iK62GelVQW6LZhcz1hXhzfWDFulp++h33Q8XKA43rNp3KmvHuiBfAVCxsQdy
  template:
    metadata:
      name: ghcr-riken-diips
      namespace: riken-diips
    type: kubernetes.io/dockerconfigjson
