---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-riken-diips
  namespace: riken-diips
spec:
  encryptedData:
    .dockerconfigjson: AgCZFunlcK0ZgxG7j5ppk+iy1XYA5JRsXFAjs++a7WNMBXojyNcdGRabas20VMqhCx34Zjbt0PEHUk4xdg6EpjlXOrq488KzSaMULbCZjLNeU4bUpfiVc8wQfLH3EK5gd1BBxdsXkuqTgLIosKCaQFU/LLsOsKMiKE3QuTBwSTZIfAk7j6/JmTIbavSZf1V5JjPlszjO5kNkxlcteklFTNYDaN4iyFMFRb0k4fP/nQx6Sls/qZJuJLFG2m7jnMGGB+JYxcK5Fh5wp416iNnvrHvJ9PaCC0nelbxZkGfh/WG2hODf5tkYCwROtWMe3RncEn4j6ZYXYH6UWsc2KmEDYibuyu67C96/Q2KRl5srzJLPfJ9nitLt+s3zAqzVSZABmOS1klEuLuz+6ya50IY21pR36HaonlzdBky08NQk4T28O8dzIQlRTW1t6yklngX0uvCgn/gx89hcAT07PEsNkITnD4saz3NMAV5vjuJdnJhWaNd6hmQnUrG4Lo+7XT2UrNMTCleUMHdgKADyCPkdOXqGd5Eyssk7m7Swdeo20TwOZIxoDSuRXkr0EbGMr72U/rDfkfJg7hturnzO8metuMPK/XaGh3+lr/ZJwY90a+FOW0C7OsYvWYlfjAmviX2PwCascB7XAm7QZyiUIjM1NQ52Qm2XmIP4AP4quf9IY7mek6N9G/T2fj8ukeurNRacPvwUJZNXIqfK8djSO9Xk1Icq3greGUhG7NDyIC2Oz4HBwfqn0JbP35NhZuFMBw0EfiCCPPtpGPGR0fzgUeRqRznXt/un9xfbRidh6R4iMf3fdP254yKF+vmNFTcQZ3qM864TDf2pxCRpQR05hwl8ktu7iIW8Xhzgh8tufpvWt45uz6428KXOkQLSZt7LENY/2OMN8Q/tCdJaxwOjP9v0++4+xUx4ovoyXAKHc2S/HlqPGcjzVkA7FhO0Kg==
  template:
    metadata:
      name: ghcr-riken-diips
      namespace: riken-diips
    type: kubernetes.io/dockerconfigjson
