---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: freeipa-rfc2136-tsig
  namespace: cert-manager
spec:
  encryptedData:
    secret: AgBQS9325+0p2lTjmMfY1s+t/t1a74Bxskbqg0jNT7WJq1SqCh06QfrNPWKwBjq0XwRBZPW/r6BqY4npcjNaAyjHiaeG6SNCPSYt54P7dQZjSFS29QzSvRAvgamerYpXxJKowqXnBCq67C4CLlalB5W0X8ECenEGF0tgxg6bg4d3KzUAVX+VWSHv0DvbxgRJFkmexIAzPoHysXqfrEq5ClWZ3BUCL1jBDqzvbiMUOJLFvDIXv1wd7r6rZW6gpwVvthjTIgUssvuWC/X6JL6By27WMn3nhPYJzcJCLGsv4s3mVhsSRMwtH6ir3mm4ZXmkhkV1RMxmC5exukfZJUPU1S+wDAuYAaAoVW+/r/k261K4E7nUe8GLKGiIoKiXZZLbrW9HzCQezpL1Xk5I5Ba3ZHks2VtS/Kk0hp/NtWv8Vj+pDUsu8XYYF5XKZoK0s1x/aTDR0KoJpm3BPAYqfFry0LJgA30xvl/fm889HbLtbdCaY1uidbJeogK0hvVFpeKbT9BzPmPEsy8RmNzEocWvt0LpV7wio+wOUlRyO1obCsOj/8FFYyq//G6ADJkileuCLyw286jdE2n49r3obT+0tjGBz3v4ANpYGoccsGoeO7cSpkiCqtRWw+il3m0DTFK55WuQ9PXvKhiI8bHOCe/eZSz0gwpZT8aqeoEvR9Wh1521rC+Gt+msd3YQ5kbOT26Btyn74aZBgVCNpOGJSKURJL6hdmCM4/QrypCasXd/J0be5HMg6XPOSK9NCEuT+Q==
  template:
    metadata:
      name: freeipa-rfc2136-tsig
      namespace: cert-manager
