---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: freeipa-rfc2136-tsig
  namespace: cert-manager
spec:
  encryptedData:
    secret: AgCxoiwP017lBje6lmOLUY+dax4YFQJ31JsFdA2RO1OZJrHlWgM6GNS7fxO2Kjyrt45muHFVu1/mtnlJMbVzpOPelWXsoxqIt2EzfbBgfOSfhKq4+FOXXlJ87s03Uxgr6Lp1lRTVEePsFquXb2GvKEY/gQFJJDZB1zF23RkyvRwGGq9qFt0G11M8IvYM37REqUobLQCg7arAVpLSuBAONbHh6gk3P3SHxS1v3wL74r8ewUIY5psDaGBbkoJfFiS+hLkUxNT9VzOPPWA6n/QtK0AWOYY56B1dT+2agOL+HhoSyTA/CrBBH/XQugLNTWwqjiAL+/PozsJ8Q6C2oCGyeIgJNhTk7N/YpEQAzRdH1bij84ZglgQq33+b1j68UtoKwojMflYdAmzACbzSPSr6L1Yi6XwobSiNUbtByLsOqoQE0U4/fYQTCST2rH+XwBdAE0EKHf9aXyZVnirIVn3hYoxcqVRdRb2AJb5jSGBNx24iopvz9kxJSLkZLmDps/Z69efl8QYEfY87heGjqbpwhU7EI7/bYBD0Z/25dLCqXwwVx8SmbpiYceLDEjwJLacs3/+hcVo2RBL7ZLiGqT8/fQxA51AZghEDrDVNdXLQalY+IO+Ug1K5ndmOh1rm2HyL5moEWluCuND91ONWSEOgDslsyIQGANzAdQQ1z7BF04JjMNAoifQJq0aYFw8IdviIEzJIwZOrJfQVFIzNDPvt1WNNc/dJCJGyluZ69AzLoicGJ0vOpPNdvx+fCZGAUQ==
  template:
    metadata:
      name: freeipa-rfc2136-tsig
      namespace: cert-manager
