---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: freeipa-rfc2136-tsig
  namespace: cert-manager
spec:
  encryptedData:
    secret: AgBzhBeiwU8y5t+S6M/cAN+AqgVyn1rwme2pwW0Fwz48jd7/Jp7mrYLuuLOapZGb4bmry6hWUaA7wfbhB3pDkT8Ju9Zt54C6k5T/zH5qp6EoMsCoxwuUe6YlepJ4ruTN+AwrSeWNJiUs9sQ32OumFvhdxBnPBDWFqyf5RKaoR36gIpMjOrOdoo5o9pn8/uZf5CUWHz7F2cu5ZX82O6C9M+qma60dFPBMEINGqzIs8qM4izvg77zeqteqlwbUFu04WRMbcIKl1JSOFvAGrevK8Z0YulVSOb/keP7eRKjCSvfvRt+RB6Ju91BhorZw2TQJiWwuS3YLaMWvmWB4+djMsbwOmBZbiLN8vdRGkscDinDYL1ftsy8U52gYdgrp16IC+0nQQgcHOb4LO4Xklj9fMczsrI3NioOdVNGfDEwqbC9E+ynfHOHoyKZZWAB/qzX6P7BliJWCOQU+8rSUdaSkvPGOevkDQz+gMHnZoLh5UQ6Mm3Wu2SpRS0FrPhHjbitIBBBciaDO9Esmkm8ocVhs8UZun21vrKloumfaBkIwHBm6RwIKKrCfHsE0w7JsYZD1VfEWVwZln8mjk7yd9klx8/YIbYd9HGd4F4PQQMm2wH4nDsmgx+3QC4SNbiaSeWeqDLf5vUR4BNFvzWL/nsyILWJL+5dfUlgY0+h3OOd3g9EI17ype/jHzyytRU20DX/C0GBIh1hBzzYHwT4cZoDWfr/91CaRQBHClTsTyEbt+C3BzCLBBoco22dn634K5A==
  template:
    metadata:
      name: freeipa-rfc2136-tsig
      namespace: cert-manager
