---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-brc-advanced-search
  namespace: brc-advanced-search
spec:
  encryptedData:
    .dockerconfigjson: AgBXeKWhDoI4z4pykE8Axy3MUsTfQ9ppMZ4seXizqw+sO7jzCXDEY3UINY8kfsOvXleS7MNmvqyXmtmOJeopYCtncjFNXvwG+kJAdscloYa21XZykmvseCzPXStf1sbSkPhLcyVQWnT6BCI9Xlb/Zxs5kusv68cYFafZmuSjWfqqzsR8ToQ3r1M5dYk/sSngkmARz36wtsNr3h1g/RgYxJpB6ktMUDZUnzqVGLMnmgSydxcziFSAC6/Wo1LXzTd5Yw5pJcGSRS2xArd5yIX4gOHxfpD1+30F+CS0TmXOXkIOOYlxkFEq6EUa3RdYEuq+MOZx0FJJdaDlAp/5joy0Zi6/+sela1TQNscEq2rA2kg09kWYlnAIJu4NWTYFu0W1qX/3FhSUDVzIABbBcbIw8QSnxMwEMKpvrF4LEp4PvEt9yJp+a9dKAH5yFVxeWoQaXhip9MmpDhbqkDtsD/9fdEkjQGsQa8dZqYIDKary9TA5e0Ta/z3iVW9rEzqjl0ySJ4hAdUcrQ+ZM7KpkmyVFHQGwvptSKbmklt5JQLFBuT7sw5YNU4WwkvvYkdzI0cFc7b6SIw0AL7PBR4B0+14EjBRrvN3lMnNyY1HrVCHCtEzrTTG+G/8LeDrpOmNikheOZIAt/aw0f2g9bOec6iRdodbjVcJovpUaMZmcRNt10j8sOstPLBIzrrlgAnmLqlG0VhTiT8I8U6QDzwcdErjIFoH9+rcoBloHFUGU9QcvYOF7wqPVUEnC2wWei17HVCX+m1iCytQqK+CK3pvlLLiGQopClpX8pT4/UgyV3wuEoz3uxzFpPSW4mIn9evA+902C9tQyZTyj+lyrDWolr5msGBv4JeKsxbFJtzNXaEPPdl8qnYi6DZ0b/4fimkYOHkZ/5KFeZaRfVFG07e6mNhlb74zEPk712M9X1s3KzYT4iSAn1sxXvgUApx81rPQdee8IRoAYeg==
  template:
    metadata:
      name: ghcr-brc-advanced-search
      namespace: brc-advanced-search
    type: kubernetes.io/dockerconfigjson
