---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-brc-advanced-search
  namespace: brc-advanced-search
spec:
  encryptedData:
    .dockerconfigjson: AgAWtf7VN+eHEvhSKVvnORzT0au7agIiRRssVdd3xS9vlgS3/jDec5wIg0D/YZV0WL+pHK1fi1HyEDr7ULzZkaf0o56HC9ppEvteWVEIvbvJGJOb1tVvR04joJUKH8yyZv5RzOxrl8hMhEfK5OAYCCG6AD9+MYYJ1C/KyK3ur3CFWAoSsluft6I655wKPIC9PJBIhvjznBNJoTktatv0aEQSBYSpEkn+DNPPviMolu8Y5H0W/Je2x7zVVZdgMVgipZivFE6O6RXHXrIEg3peegyM4hAGyeXWyNSvjaQtXr2EV8Zjtf9ObHIp51Z9nx5GGxI2/XbmkpXBRKySjLAWuuM51Kn772AuTXR/c26AuHnAF3rmKqpvvknThnSoT3BsLv6sj3c0RBSLjsDUeztZc1MrnSzpc7KY2icAVSCUo0UOfdg07a4jV1tzsVoV16PqUb5CxADc4ctKlJIADxQb4B7vQ6fZYXNbXBfUf9BhWqOjwNfC4KuwEf0xRuqc9b5VwlWoYZVggG3xOaqt9l71u9Iqe4bKleVOZr8FYkxP3cUeLz90wGfQJMYUFAfrAy0z8BsaOLMzTrWmWRYkxr7wGqGG/L6so++W9NTNFXdKmRXe+DUQcPYB/I0KhQARdtI+NCb5Zpgqw0cLxj+nR3Gk9U73dfcc0MbBH8IkzkTViBXD8PaoBgyjcMC4R/CZxaLT6QnG3/4T9NYN7MALgmc1n7/7MWK/l8TFdx1BvK1QBhdRMMhesD0MuWLBoqeTd46G178J9J7yABqXdZlD6J6TgF9iVGddQofDm70P164hOwQlo+25LsUMYHdfr5z6N7dwFSur3mKWGSK3k7z03+fxUlCKI//MuCBvXVA28e0htglEs0WmXzDzxTRerTKDrcDjrqeR0WnMLW4f1OFI2r6E3oolAsEf658+LAQ3z0RWILNo0WGym0q2ft61FA==
  template:
    metadata:
      name: ghcr-brc-advanced-search
      namespace: brc-advanced-search
    type: kubernetes.io/dockerconfigjson
