---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-metadatabase-v2
  namespace: metadatabase-v2
spec:
  encryptedData:
    .dockerconfigjson: AgBxuJ5gtder3dUbsKZgDZ1OSvPd2lmAM3Zt2Va57vhDPla7V6tgBW31i/my1eQ7I8AfqtoS1i1cuMqa/jLMMBCUbYaFqNrQ+8btYLuiCn4VwnnGEv4n4c+e9J+r+bEknc2TkLjIRp+YETjCwk0SEeFioWww1Yp+49/i0d7d2LL+377SnJ/vU/1iReTuRCm040lePNbMxjzNY45zdV/Jy9m2t/W1wd1Rpkarud8K526PQmapOWJtx0+Y19LJgV/nfDe+VwzB7CtI64vHdxwipYdt3R1Vbdz3DkRw2rBHR+PtI9NYUX46nesKojireT2vIa8Lh8q+kryG5yIV/3xkv0KNZTM/ql2yCsOufh9JqIgRaf5YdHBF/8AFv3KcN41UVmqLIQN6wXQHNcvBxlAvHJywhSFSNxOJcCmRY6mpHUiDov4r/v1zxMGSlsnR8eo9ZCDv/SiR2KfAM/7xApAvLOVyWk3Su7+ilcTWScyhlM8guHqqyetkUhL1g/ssX3Kws+NayLTJyx/J5YmkkDu9PwLV5SZ15YA18BKvCD4qvXkpOfD/n4hup1JlWFmEO3cM5EmWBVXIngh1zwj7ylOZYFgz+le/qpaeGLpApJ/w/RKRHUZv5FistxJpKGhce2XxizxXPXjDLz34NUbrDuaImekaBIHECL+1ijFvk7ch+1T+ZTRMiPyqmzkB9K53mVykaIJzM1OdiocKAP9PCZ+Vnrv8nlr0Kf8z/jKWxwLfThHyJoSrwA4HlH2htogv0/T20BtcTAGhMPZcrCliav0ToP1tTgYN3Uw/nx3iUude8N0RXQULEvAFEf8wJh5H4cIVcipGDXdbWAPjReJktblj6opVRKY4iLFkac0kayyM3Gm/R9Oa9EnloyyGnOJtM/nWX+Xss2Ep5MjTcsTuY5ujIHbolU/cXkic2nd9cz0Co3nHI63GtAApzYZ5JnzZLQ2/EUfOg8+zUe9+bD2mXtd6rXAJcwBHmGc5maAfhpcW
  template:
    metadata:
      name: ghcr-metadatabase-v2
      namespace: metadatabase-v2
    type: kubernetes.io/dockerconfigjson
