---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-metadatabase-v2
  namespace: metadatabase-v2
spec:
  encryptedData:
    .dockerconfigjson: AgAxHHEFL/w006HJwTebweTEgLHPbUvsSZa8aeZgkzav6DR0ErSf00maXpGm37JW7CjftAWly3TZHmGDKIZ4PmRKxOUyOZp5Mo69IzWrqZF48i+h6EYDnkEk4gE51+6wdTNBTrhZzBubI+eHexrTmU14pbGaGH/GYgAtqT/q/E8WNVWva7mqEbyGDfYYaf+oJKcW+QNLxPfHjELgpp5m/KEoKOZyDjrEyFhjWWxwRuuZrECEmhm5Xt4PPlyQtLhltBHDiL9x3Lj/pHGSntnzgBmXNloFTMCjStsSpLNWj9jUhwioP8yBrepk9vunWGgHSIJRktwYTdHOSdrHIPGbuv4MxC4BiF1SZ4ScS+0fzK9lDkzldIiU1GDcEDuJCXV5ivj6LQ9a+ZtBtH8FWBkQC13fb2tHJ+MqZxNsg7UAcABTnn7qZQxYcIc8r7YxAsjhcI0nD5rMtGAMA8NJ2zLKUzYkLroIAojmy9vXsgEXExrIIXQurrNNJWW4PG9mck9mdjj54T4iyBl8Mrezb1/lMM6/cFx1CokztJmS/20bz2g9yiqrExJHQgKSFAowKdRIC3udm+Vgz69FkbDzGZJTOMp+TqwZtKaiFWbevdFEgvfw+atZeEzmC1pgsLkcEXm4A9Wma2Ua/7OB3SGUUdT+st7u49mxLhWsoT3g2IE1HGOUVGwX4wzlSM7GyhZJy39QgTzYgs5uMHTHVYoiDL/K9lqgaDuUGKy+IpalsYTlA6+GtFai2SezZwwOHeG/NYgECT0qf2kRX2OVQaApTcR4XyWI9VkhGIpd8c1VJbGz1PAR0/RQMEYv3GxXcqCx6cXbC/wTt+VurhgaN4UqMKbhOKF1adD6E1+PgYYMMp6J/TwC2+OnR4Ekr1ejgDGm8Z1nLHlfDfz9y/5n1FIHTsM1Ry5gwHGWWUrb9Ctf8sy9JZjJ0kEerHQpLm+B06XBuhf9tE9tO1v+9Zl0EppeENalGWl3XSonLR87gHB0yjy2
  template:
    metadata:
      name: ghcr-metadatabase-v2
      namespace: metadatabase-v2
    type: kubernetes.io/dockerconfigjson
