---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-metadatabase-v2
  namespace: metadatabase-v2
spec:
  encryptedData:
    .dockerconfigjson: AgAM/Nb0rr2uYSsto1tELInA6R+7vUt9ZrIOdtOQkWpzRH848qfMyHDQDoNzhgIdVA7Js8zubVL4yNLm6BOy0nBScLyB4Bui5MXxYY+9Q6RZ3YW4xh5LCFTcO7yhlNf5RFebD5te+VPnmDe1/FSlKE3fdCuUd0bavvOz/ibq62G1wG9liXK446dppKHI0OLPe8KissUcBwkioJcUvyUfHg7jcft7b6B5f6lNTtZ+mOnrh1n7Uw9Sqq+ABepTnweErmW4LT3UQh/3mMHS1OCFktb+wTqOz73abgtGC9iopI9jWHuxfVi4QO0mDlXZPT3drQvcUYNQ47LNcUVhsDZL84OhvbXd78hyfShLN9xMkxPU6U7h6/v2/AueuwgTKM75dzG4QCHSSyikbaFoSeHI8vl+/3+Ow/hT5cihpCI08vORNJjCloGU9pezimsKgr+NybaXTmZ26QyD3xbKYytunbtjDa1568RDAmeqwfoSbApXnXU4YhZE2rB7f9WqzQ3W6rpLMkeTh2tkc1TqqxeQO0kG/4unH06PquUki3TE7C8m7kzvsMSkeODKVxfNdDV+T/BJ6S/97VHO+tL+GiVuMyifghfVtUV1jZXc+6jo8EXRCetmT7LzDgZWlN7ZGYHkjjwIJb8CCI47E2cMRkP/KjSM4TJ1HKDF6TfOMWdqcX1ByDhGo19RpnXoP4anXwX6PRlnAY20ystNHItqXOHqEf7riQ1L+08g3lriPzLl4Ixq3VEmKXUuuCUAmQb9/EDjUkPNlmvKp5kkoxXdHC/2hFObW7SyiOiRC2oH83CrfrDCPN90iHzF0FyCWXyYshMreVFQx98psRidb4YmAsKbJnjQnxklvYdBxqbgEcoAPOqh7gtMOcdNvi5P7Q2VDisi8tGKk6jzg79M/bwbjbethv93C2s9goFgqFKWDIOdpFg5C1l2Rtpk/h6rH+JVF9R8VbopR4BDIsL9nkFuvz4paw6NVwDDZnx0yXjO0xoc
  template:
    metadata:
      name: ghcr-metadatabase-v2
      namespace: metadatabase-v2
    type: kubernetes.io/dockerconfigjson
