---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-riken-diips
  namespace: riken-diips
spec:
  encryptedData:
    .dockerconfigjson: AgAJHRsO90fZMEJrYiNmUeGCfMONMLwKcn7waQVn8ISv+qkspgz11kivuCHEv6mhiPVVeAkGWRW2dijx7l/yiJhjdvggRNai5Yurn41My6aaUBzZsMl7PqLS6SC3SUiQJCpmiG2W/ZoNsL4Gv+XFZDSqXWILoGIR2E+CpCpLwkjAvlvJDXgJE+wJ/9/sashc9aiFPVcfgJhfTcAsn02opEzk/llTxDoOtAE0F4ZEdIy29mJPNzUxLRZMHCijfP6AmcKVIu+EsbG0qMuVIkAQpeFcaHeEh53p2QOk02aRSbdRmXuQXzN2uBR6AHb2vdOhNUfWrp7R7uMNsN6B2vTfdDvIpkJGnvY1VD8bDUJhVf3fYMqDV75OflQ+nvjTTWCESGnWL0jGl57r42o/dJny6kykL01sEcdPayO0NL4KMqqtZXuGSMc9aPQB28GN42L/4prpFLk2aroWMA6z4CvrdGQ47ZfvxG+nXsXwz/vH4nGA6CnL59qTK2zs8+Sq4yQnGLJ9zdyNiTanRR4rXREbjV2FfuzKAQBCkdx6VQGdt6/1hx3fedcID8qGzyJ70m4cSyTATCtgFktKbrQKx3QO6xItifnZ3nJCDFfE5dC+V1VSo1sP03t4cONr1yjZ7rA3iGNs8LscIE8+gLkGsdK7bvENGL27bQ9SEf/Wl+PWCPLFUoJulZ1s+VGnTJD2dtHvax6SNVhgudhwYp+DubGE/4N4UBY3IucFtt7UdVBTDoV/G6PBml5+NBciQErhflWAwi7NpFACoJaZBHX0G1e/OPd1+71e1I7tdrnJ62zwfUtqIseidzV3hqtX882GM584v/ntlFDKrH/F6dU1yZWv9de58K1IBC5ZNdo8ho9uFM8gxLTt9C88FdQ3Tl51+6Br4jtV7F0okht/72J01UeUWjAcIdqgrZbATUJOcd93Ec1t/ddpPvG5n6isDQ==
  template:
    metadata:
      name: ghcr-riken-diips
      namespace: riken-diips
    type: kubernetes.io/dockerconfigjson
