---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-riken-diips
  namespace: riken-diips
spec:
  encryptedData:
    .dockerconfigjson: AgBRcoT1YaKv82K2vGnwDfOZiHc/J93ZokFvjSGAx35dtddssLhKLbQGqQua44MJmYNwQ9yJDhh40eYp8s2tXRO1PtGieTNWiiNPOkujr7wJEr+Ms8HusAeAOEVG2sOVEfRQHIpmd2IYAMRwlgMcpvkKCd9svaZFhrQm+ZTcks8OcDTrwJhBv2OL9k5IyanaTkLocqSxYZ2lgKrOpZ11+xQAnnSZz2Kq3cWLN9C47i0kNLDR7yGMB0md9WoQHZPjgDCVmWsiZSLLPpOUG8L7IOSrVBCSKI74DGkSdjYmDrNWhFnt/82V0qWU6Y17a86RGoNSkIFSLrj0S3mzTpROv/82rHgIihyBZiOugMYnuAGsZtNnAhdup1ShY/OWpH3wt/DGQv3Df/vL1uu69wm+DmJvr8Kue5JYBSVagTS+IIqMkkVM+eBvidN/5F1LHL1Eyn2b43l3cVY45sQs7ftWQ5hdfa88sZ5yp9vVyQZcqArtzAr1x5dRVD9y9rJ1xltLVnuMaxCZKkBX9OdWxt0r4sG9GFhcv2gDwm7KW2cIuOS8FvmCi5W6hqtdnpa2x4LoddyDzl9GHvsWL47jUwRwl0rQpT5xM1Ru4s5SGQBzSAuAmV6eTR5l9Y9rS//OLbaL7/Q8iGlD005FYBcknDNVRAOsZRJhpbrotujw7Wkd7tPA/HAbLRGM8u4oBnwZsqG9OVm+WGmDdahpwJ7RXO+xxRrpKdR86GfAO1TwGNrZfTOyNowSb+Qq2f3uxlOXj7SSRa1eNmGeH4+RAYzWT/5Lp2O1ne00IvOnvG4IzJ0LXCdKbgRnfQHZEos7KtUHbBVlFIS2Xrfm5qHJeOFgBr7rtZq3cd/Mge1yfFm8fA88LLMst9mODtWAXzsu+JproHzR1d2uef0jpGYaQDyxfEx2CN3ti/iI/1+uUDdattBWxq4djzCec224Wt0vrS9oQbMOEPpbx0SthYPH3n8vh2Slorf+UjjvQNJ64Pql0AlO
  template:
    metadata:
      name: ghcr-riken-diips
      namespace: riken-diips
    type: kubernetes.io/dockerconfigjson
