---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-riken-diips
  namespace: riken-diips
spec:
  encryptedData:
    .dockerconfigjson: AgASTGgXbaAbMOKmrHc5qz5/b9Ih/axtLX1r2ggzwxIUpd+WqEuzAjLd18JVYhp56XDo/Vp1wZRQivdzl+UkXk4IDU9fBRFncLP6G5C4h6WOUzETfVTW4rnIBMVzjBVkRyNaS+g8nDwr7e9eAHuk7a0/H2DPd6HVWj21js3yk41c4GFgMKCcREzj6f6Sm8qYD3TCCJM8CQUz5lwHQiO+nhWcDNcO3dejxdrNKTFS48bOmf8j72yMy13mMFtAMxS/OEiWrJ0TrdCQ0iR94htzsC2Fhf4h9PxiyTOs4O/2vUcMpK4dmWW5pIO+O+qNp1gUVY/L+igZ3HG4Q7ay77YfH/EFrh7AteAEMr/PRXuvhzYbjhKfW+U0FCOTk5Il6XFCaoelrYIbw5XWb8+wrTaeXF4Y5Gr6WGiN2fXe+gxTAbpdcXYjGB8Bd2qoITggGTkhFGpShmnqrih36KAlOLXToTFHoGPDjUCFiWJaUoHhorlfhbt2EaZQq3p2tpNnKTz19WgyB4Hu2bhP1TZghaTxKct2rQo/iGelaWzMtF0uUW9ssalrix+IlkTeUPNpnRL/2Nd06soK6nJ8dCwlfbkM/kDaaNGNOa0bHXhPkL/i24DXmhu4Ce5Xv0KbsECwe6U3uvWrE1Y7BQEd8JFowtTbAXZ6QR+V9ihpz5594nLOBVOyazK53CQZfwy7SHX5qm143WXYMXQ+ePpHQtiPmkhDFueFRGsU+MkOHSd+f0n9S0VjkwAM2kUgvK0iRXTsTvrtXM9+8sADi9mOvj6szgqa4Fon+DqFQtNXGvadvW/hXHBX6RhhtsATE4Scr9Ck4t2jcpY+NSTbiQdKROGxssCUuYrfJlgeT7d2Ah5h7v8jDW3KTSx9qON0VaLhI8ceT7fsVLf7IN5iAKuPHtzePhfUL7KYOoKJ3bRinnf2j4qOZ8gliL5JDk4nRk+WB3ZZ/N9WnefqTFMaEM/yawNewDtA3z6cnQCCT1rcPb1sk3ND
  template:
    metadata:
      name: ghcr-riken-diips
      namespace: riken-diips
    type: kubernetes.io/dockerconfigjson
