crds:
  enabled: true

configInline:
  address-pools:
    - name: default-pool
      protocol: layer2
      addresses:
        - 192.168.1.150-192.168.1.200

  l2-advertisements:
    - name: default
      ipAddressPools:
        - default-pool
