---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-brc-advanced-search
  namespace: brc-advanced-search
spec:
  encryptedData:
    .dockerconfigjson: AgBfZohu1yDfxPR2P2g1L9+QrWrAh5SkfP/49PqsYF5+GsRAe8XLJrFAVu91O8l6Bb94/t5rO4gmKGTguJSxoaOQBpzFfNhWigEW8xup1NIG6sfNmDegtgxKMaVr4WUTWpcGJyjPLvwt6a+bElsqGb6IWl9SnNeJH1HK+0Fe3ipaumWPTE/dp7QYcF46n3vEdW+9sOtchSRkNX3RuQhvUTuQH/WuBrmqT4huDJC/XTTurTwyq/6gx/Fzr15/pT7XhLap+9HxPr0vXtSKCZk+aKUOtw572ZSOXw2dVqlLLRES9V+bSgMiPZrIwm9eECDDNsWuoSxHhr0hZNxRXk3rg/PNrUzwG74TIyXE/86DNhXs9cZwkrGjPLZ25bURKD9poqhBMSMmOXbEVojDL4DbUT9s7KAYCDnX6wl58U3o6o66PBxFOtbuYy/jIhdH1gECpoofYc2yU3sRcty/atTA5rBmiZBZKkOB2pi+MADnoSZL+JL3UI5Pln4lu311gv+DRfcxdWDe6wsyXcv/ItPLJyyU7Kr6TrR6gqkcfB8zOEFPIe6eCVVvlxgLPBXUO5UYz1yo0XvKsArjFCHOIkgNoOMlS5Yx6/gRvPtbpwVMGeau/X/3Oe7GctuJ4eLQzbg/xZWoQhcaPyx8zS4utKFlE46h7p7dBYJuk1ipuuGJW7feParbNxbeGXEuxfb+2ySQFK5/pTBoacq8ZxdSux50TFsz2wk+lX1nZfwIwyqjmRYQN/0/PGINrNWEja1PqE76n1NOX8ma7O37Ttj2wUC07akkhC7BggBv1wnQa12cAG2ZOSsL9lvGMia7KCof6XzBabWejGBrS/NGRWONgboiAVjVDlC6AuKIHqfk3C8Bmhr/Mt5qPXtFLB9TlKFSL9G18ivXuJTVk3UsuVNSN9GJT2f3RTbj02ljoCoTao3H3QjBca4ZA9xPEHwbWplR/2WD30H46qBlnmsqeEjKd7+w31lSOgAFcqCqaDzg7xdF
  template:
    metadata:
      name: ghcr-brc-advanced-search
      namespace: brc-advanced-search
    type: kubernetes.io/dockerconfigjson
