apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: freeipa-rfc2136-tsig
  namespace: cert-manager
spec:
  encryptedData:
    secret: AgCYWpBduHwOwN26WwPED0sIIsPa3kpEYne0KR6dHpZKaKgdpPVuBWJDGKH3Y8kt8zgeQKfD7QYAr7nxOuftLGGInVfFXnNbQyz1XnKl8ytj8pU+upd7QOvIdVfvvTDuvrI0qnZ5wbQ5N0KXzZS01vtRfmmzn9ZzZQXc3hX/HtWUh1fSeCVErKmDG7VfNoL/bMPnb9ojIOCuPjxupQxaw4h1rhs8Z8eWNXL+AYp/A8UfLF60P6SZ4cSRtTdrGGd/BfU5XMahVPpWviQx/oOrhtx6EZ8h4mbKx3933RaBd2XnkbBt2+/ETRROJYhm8F+sBHKQSdUqxsqzhtn2xfHzr2BfrJr5XDZsAhbzOoUmpFRKVuaYP74K7km0CyLxGNfcJa3+0/DN7pSaD9lRll1IYIvpgp/8wLEdVJEXuJayFWN+wSQf8/ty443xWvFErS0Eg/yeXBn5BgSZQHzhZByGSHpuW7IP6xt/OyFLtCehtaRZzJoqaJ6zz3PiaGrykHBLhzUezBMSzWxGjr4U89ejNOfCu3/vTYBJqtoPbaZLzNjVUCfLI8+C9NwiH8bmjucFbDHo9k0OMu7qIpDNmWZ9SNyTeUN3ABCcPJ1jpX1NlXP9esTfL9/xWsNKJCLZ2ZFHxSxhtOqrxz48ldlgt+CSvhIMNmL/ISTQedXbapI0dkzLmU+2BDfzhbcuu2m1XcXQexSPoBHOhN9gH1RWpWH+T1k5+d9mKivNGNcL7sJRa5ejNLuhbt6h9B4QWI81JA==
  template:
    metadata:
      name: freeipa-rfc2136-tsig
      namespace: cert-manager
    type: Opaque
