---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: freeipa-rfc2136-tsig
  namespace: cert-manager
spec:
  encryptedData:
    secret: AgBJiY/vns6rJXRhqEwn5q4Pk84gXYQVBTcenFfnyEWC+FoxcaMG0+4T6wi3Ucc+TL498B+L+niH4kUhNNtimGWAgKMfsdVCmYd/Q9FftuVAUmY8JuffgV1UsuOlGUC0QFTTr3I9y+decPoI8bpxX5T5lAPGcKI6bkFktrZudl434m44d6dUd0PJH/43OAdr/WahOx+o/uepsfB2Trh/Q5wx42ZPYZw2s2t7QVjvaN0POZ4HBYUf07Q7W6/zNlk3yTZHfo8vzcT7idYhgx/vgvXzlRk+MOpzBKXlsEyw7qZk5zz8ObkahDMi4isOXXwtlOixJbP0Ca5ru2ygaVGWdxo3DrCn69Rp6EC0TKMsebVrqzU2AvLeB/TYzS91ykqzDX8rjZbfaX4V6+TmBuGrk7FMRh/HLUnIQR3sn8dpWFobizMJBB7UDsnrA7rzTTiHPkLIa/lDcLL8n7J14rRC6Zf98GoyJlYvcGcoH/FxOHUUVCMONYZTXCWxsVLCbcsgrV2QuHl7ZLGiaxypAP2M+OGzFrsFOXa5Kvxz8qEbrL4hQlLIQcSVXIQWCFmjbinBlFvt9k7ykU3tI3K3h3FI4Aa9hUIClasKNrSdyiROQuh/HJsTb0PkGU/LzifelCEDXwkCAHOf5rJXG6onR86ISIp1dsmH923LUeBHYGBoWAz0a/5mOSE/tTaJBKQb1PXQNOZQWEvB44+k/UIiVaPnSflLNhshabx8NEC6/dhu7k0COgucA3bUDQyxYpiyLw==
  template:
    metadata:
      name: freeipa-rfc2136-tsig
      namespace: cert-manager
