---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: freeipa-rfc2136-tsig
  namespace: cert-manager
spec:
  encryptedData:
    secret: AgCR0kLKLo0MU2lb0Of7RP3TCInOnXvdzoJqCX9t/EhDS1CjenSsdtrNYjORhiA0hkcMdOxWQnNxVdRt80RA1hF7LVrUSI1wJkSAmjHVXsYUfVUJ9MSpgxzNrBL2KqNg8rUDFkYodZEL6o/MrHHSA8nlEYb2UWCxFl/8aBlgDOO+XQanqIrDn1A7gBahG6ETD29oA9DtPsA9GTVoxE5sqm+leVptRQ54Y83XYQA6UNQwBgu49ItNRJll3Ujf8CbEr96Skbp9vYmKsOUHk51NmB2b8leXYbVYd4fe6s6TKeSjN3jSgRnIbUk5egSd6+M31ysi9iUD2zjoYjXK3tkWJ84AYCunZ9m7GGilVgjO7MV00WZoizMrU3Nv9uZZJAw91SK8rQs7ZlJJyN867/UAVPliGE9UXyE3f+A/YBxpbD7LsZ4lKLg+qjWBR6pfcfa1aOIyM8jL4NW/qj1fK65+wMTaX82tJpBEJDoe3AXBwe+6hmo/pGIcO0VMiMrl/0xIR6Fiq9ZHfSJY3fY5d6ndINHE8FfQ+jabdkEEBElZEJSkJql77JTPIOs/LkSPnXWsgvI8PgD8YW3UAKdEoGCoQwzC1MYhkfKHYQAbI38Rsl4AeSL50KTBFCjTZYmQBGpAwfEdXC3qKhL/W6xcF7BztE2sFNbDbMxLe3hwn5bVoSmJ6s6mKd87xSvsPvk496lU/kzsIY2hZgsDpT7mSSak0ewplWJDhqSFEkin4B8760KKgDJzWxYECNGzjDCsTA==
  template:
    metadata:
      name: freeipa-rfc2136-tsig
      namespace: cert-manager
