---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: freeipa-rfc2136-tsig
  namespace: cert-manager
spec:
  encryptedData:
    secret: AgB0eDdUf6SfiIxh77kNmX8Ke/6uqlhpyzf13ORCJcrBNfynb4UWm7lz6kn2S0rX4lq8qqWQP0Ju18TL2BPFyrmmZc+rAlm5Gl8uwTL+ir+1OhjaqZMspq7QCA8DmYdqJLSL9zUsuOdCpwcMMFni23PCz7HPyfyhujYZDmztmCwJ9WHkP/fGU1cKEhS/xovpuCkUn/B2tAYkDgfCk+XwONtXYRfOJ4Xa14we5/t2u8NpPLwF0YAoItdS+tm3xUrKo6xC9C7ottpJRVYZOx0OlIDr8fOlAaNQpPM6ghSRCbb8F+NCWBQx1D0EE2C1cJEhSTCDT+Y4Ngb9lAbedbKpDSetykGJsZoxCe8UIARVZQqGkqjVA7OHZoqchbxz3+D1KZ4UvQQ646VwS00dAm8QxnSliMaynbYKlAXZJHu56h0R8RZx2XtSDIQT2AWoGXXcPDIF/6mY9SNKgBuXLvqrHiHD4g5Z2YKRdJBdEw9gTLk1CDevfYmTsT7R5NTLhtBC5C/vgeG3O5uyDo43Tzb8IbZiZs/XR6vRZn2rU7CzERsOU+qYQyiDtWuIeOTbnTuFBSg3V4PB1muQ0S4F6oVAI4N6IvlVsYR3M0EQd4D4iRdl9TmyssTJc6+7wjO+Sy2898mdxv13DiAX4CfP1Do5tCJ70Q3e8Mmguxl6LiHroWpSWlVQQnC/ZeuCWF70sdet6eHemRcZ86UT9XHUh3RPvwsc9MTTGLDHbsFxN/Pyfp3ktxB5/Dx8uDstsygf0A==
  template:
    metadata:
      name: freeipa-rfc2136-tsig
      namespace: cert-manager
