---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: freeipa-rfc2136-tsig
  namespace: cert-manager
spec:
  encryptedData:
    secret: AgA/iDHiMfOFXQlu7vDOynkQpTdES23rNZmLPI7UOZB9C7vIrMzj3xrrO6Y1S78LIE1gAozggKnzokCRfzzNDW7SaxElHvZea41I7v3Fuj6YFSlEuqijJdAkGInE7EGvbqkWzxM+9Vi89uRWmUfQrfiiPmvt03Xfastbr9etugnGivAWsV80czJY2u/z7T0ndGleeccmbKpBfhliF5R19Xdxsl5urme74rxZDq6vowhlBOdFhzm7a7SWSu8vobYrt4eOpPCk1rTIjNdRm/ptzpzVZvq3dx3j4v9mtEYJfotM2Stf4D1pn2aY4G+AtHF1Xhn7JJOdupyhTtfPdkTumCQOkbWbrT/JmoY+SdCYbRX+qqFnZ7Z6DocpowfXESVbrrlvifJJCwOVpR9PlV/5ueMO31AjVtVZXPlf8h3hYYXXETQuaeldMTY18USPZhf3bwl67Nv5pYVQj2U4ro88ln2xIcj2DSWHH7KSt+wfjM/mEkH9p1YJu6HUh6nI3zgVZZhuWmWq6UqG041delVX/+znMva0vVG+S6GBfpSZJnVxw9zHXiOys+kb9W3uVGI02KJbf3wrN/atRPTHxyRFm57ViRv5952DNrfj/CJo+VTX7kRPr27F1PNWa6qTfteFxVgqaxexV5d/aq1VAi1S2ag/UfEnRBFE0LMsqc8Wp0Ppjheco2CF4K0Hy5v6f4kG+jHG5AlUp5PnTCutijTtLzeKRmWtsF+ZTepkbxK1E4vnpTP9EF1Gf+E04SCmjg==
  template:
    metadata:
      name: freeipa-rfc2136-tsig
      namespace: cert-manager
