defaultNamespace: longhorn-system
targetNamespace: longhorn-system

# バンドル削除時にCRDを道連れ削除するとLonghornの全Volume CRが消えるため、
# Fleetにリソースを削除させない。
keepResources: true

helm:
  releaseName: longhorn-crd
  chart: longhorn-crd
  repo: https://charts.rancher.io
  version: 109.3.1+up1.11.2
  values: {}
